### PR TITLE
Added testcase for rlon=0

### PR DESCRIPTION
**Pull request by efmkoene**
This PR adds a simple testcase to check if the performance at rlon (see issue #6) is correct or not.

### CODE REVIEW

**Comment by efmkoene** [comment]
Hold on, even though the output grids clearly differ between the variations, the `amrs.nc.compare` doesn't pick up on the small differences.

**Comment by efmkoene** [comment]
I have modified the fake (artificial) emission file to contain values a few order of magnitude higher, such that the error of the stripe is now larger than 1e-8. So, this PR is now ready to be used to test the errors (or not) at `rlon=0`.

**Comment by gkuhl** [comment]
Thanks for the pull request. I think this would work best, if we implement it using `pytest`. To make this working, you need to rename `performance_at_rlon.py` to `test_performance_at_rlon.py` and change it content to the following:

```python
import os
import shutil
import subprocess

import netCDF4 as nc
import amrs.nc

import pytest

def test_performance_at_rlon():
    """\
    Execute processing case which has rlon==0. Hard-coded (in shell) to save
    effort of sending in all correct arguments otherwise...
    """

    # working directory
    cwd = os.path.dirname(__file__)

    # remove outputs from previous tests
    try:
        shutil.rmtree(os.path.join(cwd, 'outputs'))
    except FileNotFoundError:
        pass

    # run emiproc
    subprocess.run(["python", "-m", "emiproc", "grid", "--case-file",
                    "tno_rlon_test.py"], shell=False,
                    cwd=cwd)

    # compare output with reference
    out_filename = os.path.join(cwd, "outputs", "online", "outgrid.nc")
    out_filename_ref = os.path.join(cwd, "tno_ref.nc")

    with nc.Dataset(out_filename) as own, nc.Dataset(out_filename_ref) as ref:
        assert amrs.nc.compare.datasets_equal(own, ref, []) 

```

You can then run the test using pytest:
```
python -m pytest
```

It would be good to reduce the resolution of the country mask to 100 m to speed up the test as it currently takes 40 seconds.

If your fake emissions do not contain any data that we cannot publish here, you should also add the file to this pull request. I think you mainly need to change the attributes.

**Comment by efmkoene** [comment]
Thanks for your suggestions. I submitted a new commit (with typo in commit message) that follows your suggestions.

1. I made a new emissions dataset (the one I used was 900 MB) that contains only the bare essentials (`CO2_FF` for each 1x1km area). No attributes remain at all. The resulting file is 60 MB, but when zipped it is only 219 KB. The unzipping takes place automatically in the pytest function. Seems to be fast (<1 second) to unzip.
2. I use 110m country lines
3. I submitted a new reference file (as the country-ids are slightly different).
3. I copied the function pretty much as you gave it, so now it runs with `python -m pytest`.

The only problem is that the test doesn't appear to fail even if the output array is clearly different. It seems PyTest doesn't quite understand how to interpret the outcome of the `amrs.nc.compare` statement. Do you have any suggestions for this? Alternatively, we can just read out the data from both output grids (`CO2_A_AREA`) manually and compare those.

**Comment by efmkoene** [comment]
Thanks, that does it! With this fix, it indeed fails when the two datasets differ. I'd appreciate other people to chime in if the test passes or fails for them when using the same setup. It'll always be worth checking the output `ncview outputs/online/outgrid.nc` and see if it contains a vertical line for the variable `CO2_A_AREA` or not.

**Comment by efmkoene** [comment]
I tested; the test passes when you use an earlier version of `cartopy==0.13.0`, which can be installed with the proj4 library at version 4.8.0 rather than 4.9.0. So, it's more related to `cartopy` than to the Proj4 library, seemingly.

**Pull request merged**
